### PR TITLE
Changed Joined! Formatting, removed false Dates

### PR DESCRIPTION
**Pull request by Nanabell**
if you wamt true joined Dates. I'd suggest saving jointimes in the db not code them into the bot

### CODE REVIEW

**Comment by freyacodes** [comment]
Are you saying that join dates provided by Discord are inaccurate?.

**Comment by polo123qwe** [comment]
he means for people who left, also I'm doing that already in the new version

**Comment by Nanabell** [comment]
Amery HardCoded his and Yuzy's JoinDates. what i meant that if you want to save the 1.Times joindates

**Comment by AmeryKr** [comment]
Literally fuck you Nanabell

**Comment by Nanabell** [comment]
if your gonna hardcode it do it correctly LOL

**Comment by AmeryKr** [comment]
It was correct, though. That is until Sergi added the other shit

**Comment by Nanabell** [comment]
I dont mean that its incorrect kek. i mean with the period. I Dont know Js enough but just parse it and do the same as below

**Comment by AmeryKr** [comment]
Then don't come and correct what you don't know

**Pull request closed without merging**
